labels_dict = {'1':'1', '2':'2', '3':'3', '4':'4', '5':'5', '6':'6', '7':'7', '8':'8', '9':'9', '10':'10',
               'A':'A', 'All done':'All done', 'Anniversary':'Anniversary', 'Afraid':'Afraid', 'Angry':'Angry', 'Aunt':'Aunt',
               'B':'B', 'Baby':'Baby', 'Bored':'Bored', 'Busy':'Busy', 'Brother':'Brother',
               'C':'C', 'Child':'Child', 'Cousin':'Cousin',
               'D':'D',
               'E':'E', 'Envy':'Envy', 'Excuse Me':'Excuse Me', 'Excited':'Excited',
               'F':'F', 'Father':'Father', 'Friday':'Friday',
               'G':'G', 'Good Afternoon':'Good Afternoon', 'Good Evening':'Good Evening', 'Good Morning':'Good Morning', 'Goodbye':'Goodbye',
               'H':'H', 'Happy New Year':'Happy New Year', 'Happy Birthday':'Happy Birthday', 'Happy':'Happy', 'Hello':'Hello', 'How old are you':'How old are you', 'How':'How',
               'I':'I', "I'm":"I'm", 'I love you':'I love you', 'In-Law':'In-Law',
               'J':'J',
               'K':'K',
               'L':'L', 'Later':'Later', 'Listen':'Listen',
               'M':'M', 'Monday':'Monday', 'Mother':'Mother', 'My name is':'My name is',
               'N':'N', 'Nephew':'Nephew', 'Nice to meet you':'Nice to meet you', 'Niece':'Niece', 'Now':'Now', 'Need':'Need', 'No':'No',
               'O':'O', 'Once upon a time':'Once upon a time',
               'P':'P', 'Please':'Please', 'Pressure':'Pressure', 'Please wait':'Please wait',
               'Q':'Q',
               'R':'R', 'Relative':'Relative',
               'S':'S', 'Saturday':'Saturday', 'Sunday':'Sunday', 'Sad':'Sad', 'Safe':'Safe', 'Sorry':'Sorry', 'Step':'Step', 'Sister':'Sister',
               'T':'T', 'Tuesday':'Tuesday', 'Thursday':'Thursday', 'Take Care':'Take Care', 'Thank you':'Thank you', 'Today':'Today', 'Tomorrow':'Tomorrow', 'Tonight':'Tonight',
               'U':'U', 'Uncle':'Uncle',
               'V':'V',
               'W':'W', 'Want':'Want', 'What':'What', 'When':'When', 'Where':'Where', 'Where do you live':'Where do you live', 'Who':'Who', 'Why':'Why', 'Welcome':'Welcome', 'Wednesday':'Wednesday',
               'X':'X',
               'Y':'Y', 'Yes':'Yes', 'Yesterday':'Yesterday',
               'Z':'Z'}